import { useEffect, useState } from "react";
import { RefreshCw, Telescope } from "lucide-react";

import { getPlanetFact } from "@/lib/planet-fact.functions";
import { Button } from "@/components/ui/button";
import { Shimmer } from "@/components/ai-elements/shimmer";

const CACHE_KEY = "cosmic-atlas-planet-facts";

type FactCache = Record<string, string>;

function readCache(): FactCache {
  try {
    return JSON.parse(window.localStorage.getItem(CACHE_KEY) ?? "{}") as FactCache;
  } catch {
    return {};
  }
}

function writeCache(cache: FactCache) {
  window.localStorage.setItem(CACHE_KEY, JSON.stringify(cache));
}

export function PlanetFactCard({ slug, name }: { slug: string; name: string }) {
  const [fact, setFact] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);

  const fetchFact = async (refresh: boolean) => {
    setLoading(true);
    setError(false);
    try {
      const { fact: text } = await getPlanetFact({ data: { planet: slug, name } });
      setFact(text);
      const cache = readCache();
      cache[slug] = text;
      writeCache(cache);
      void refresh;
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const cached = readCache()[slug];
    if (cached) {
      setFact(cached);
      return;
    }
    setFact(null);
    void fetchFact(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [slug]);

  return (
    <section className="rounded-2xl border border-border/60 bg-card/60 p-6 backdrop-blur">
      <div className="flex items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <Telescope className="h-5 w-5 text-primary" aria-hidden />
          <h2 className="font-display text-lg font-semibold">Nova's fresh fact</h2>
        </div>
        <Button
          variant="ghost"
          size="icon-sm"
          onClick={() => void fetchFact(true)}
          disabled={loading}
          aria-label="Generate a new fact"
        >
          <RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />
        </Button>
      </div>
      <div className="mt-3 text-sm leading-relaxed text-muted-foreground">
        {loading && !fact ? (
          <Shimmer>Consulting the star charts…</Shimmer>
        ) : error ? (
          <p>Couldn't reach Nova just now — tap the refresh button to try again.</p>
        ) : (
          <p>{fact}</p>
        )}
      </div>
      <p className="mt-3 text-xs text-muted-foreground/70">Generated by Nova, your AI guide.</p>
    </section>
  );
}
